name: 'snowflake_test'
version: '1.0'

models:
  staging:
    +materialized: view
  marts:
    +materialized: table

  snowflake_test:
    data_spine:
      +static_analysis: unsafe

vars:
  snowflake_spend:
    enabled: true
