name: jaffle_shop
version: 1.0
config-version: 2
profile: snowflake_test

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
vars:
  dbt_meta_testing:
    required_tests:
      staging:
        jaffle_shop:
          "unique|not_null": 2