name: 'snowflake_test_ci'   # Project name (just metadata)
profile: snowflake_test
version: '1.0'           # Project version (metadata)

models:
    staging:
      +materialized: view
    marts:
      +materialized: table
