
version: 2

sources:
  - name: ani_staging
    description: "Staging database for GA analytics regression testing"
    database: STAGING
    schema: ANI_TESTS_SCHEMA__GA_ANALYTICS_REGRESSION__ANI

    tables:
      - name: order_items
        description: "Line-level order items from GA analytics pipeline"

        columns:
          - name: order_id
            description: "Unique identifier for the order"
            tests:
              - not_null

          - name: order_item_id
            description: "Unique identifier for the item"
            tests:
              - not_null
